language: python
sudo: required

services:
  - docker

install:
  - pip install requests simplejson 
  - make docker
  - make run

script:
  - python test/tests.py

after_script:
  - make log
  - make stop


deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: key-value-tarantool
  on:
    repo: Alex-Kuz/tarantool-key-value-store
    branch: develop